#!/bin/sh

set -e

PATH=~/bin:$PATH

if [ -d "$(dirname "$0")" ]
then
	cd "$(dirname "$0")"
elif [ -d ~/Censorius/herald ]
then
	cd ~/Censorius/herald
elif [ -d ~/Projects/censorius/herald ]
then
	cd ~/Projects/censorius/herald
else
	exit 2
fi

mv --backup=numbered herald herald.backup 2>/dev/null ||:
mkdir -p ~/arc/herald/
buildapp --output herald \
	--logfile herald.buildapp.log \
	--load ~/quicklisp/setup.lisp \
	--asdf-path $(pwd) \
        --asdf-path $(pwd)/elephant \
        --load build.lisp \
	--dispatched-entry herald.cgi/herald-fcgi:exec-cgi \
	--dispatched-entry herald.fcgi/herald-fcgi:exec-fcgi \
	--dispatched-entry /herald-fcgi:exec-cgi \
	--dispatched-entry herald.repl/herald-fcgi:exec-repl
ln -f herald herald.repl
ln -f herald herald.cgi
ln -f herald herald.fcgi

echo '  ★  ★  ★  ★  ★  ★  ★  ★  ★  ★  Victory is mine.'

BUILD=$(< ~/herald-latest-build.id)
echo " This build ID = $BUILD"
cat ~/arc/herald/herald-build-$BUILD.log
cp herald ~/arc/herald/herald.$BUILD

echo "Version running in Production:"
curl -d 'verb=about&deployment-marker=t' 'http://www.fpgrocks.org/reg/herald.cgi'
echo "Version running in Test:"
curl -d 'verb=about&deployment-marker=t' 'http://www.fpgrocks.org/reg/test/herald.cgi'
echo "This version:"

