#!/bin/sh
echo "Version running in Production:"
curl -d 'verb=about&deployment-marker=t' 'http://www.fpgrocks.org/reg/herald.cgi'
echo "Version running in Test:"
curl -d 'verb=about&deployment-marker=t' 'http://www.fpgrocks.org/reg/test/herald.cgi'
